name: experi
on: push

jobs:
  ranjith:
    env:
      name: ranjith
    runs-on: ubuntu-latest

    steps:
      - name: Print Name
        run: echo "Hello $name"

  kumer:
    needs: ranjith
    runs-on: ubuntu-latest

    steps:
      - name: kumer
        run: echo "HELLO $name"
