name: experi
on: push

jobs:
  ranjith:
    runs-on: ubuntu-latest

    steps:
      - name: took at repo
        uses: actions/checkout@v4
      - name: install image
        run: docker build -t welcome .
      - name: run image
        run: docker run -d -p 5173:5173 welcome

  kumer:
    needs: ranjith
    runs-on: ubuntu-latest

    steps:
      - name: kumer
        run: echo "HELLO $name"
