name: experi
on: push

jobs:
  ranjith:
    runs-on: ubuntu-latest

    steps:
      - name: took at repo
        run: echo "hello"
      - name: create file
        run: |
          echo "hello world" > file.txt

  kumer:
    needs: ranjith
    runs-on: ubuntu-latest

    steps:
      - name: kumer
        run: echo "HELLO"
      - name: download
        uses: actions/artifact@v4
        with:
          name: file.txt content
          path: file.txt

  ravi:
    needs: [ranjith,kumer]
    runs-on: ubuntu-latest
    steps:
      - name: welcome flow
        run: echo "MASTER"
    
  master:
    needs: [ranjith,kumer,ravi]
    runs-on: ubuntu-latest
    steps:
      - name: welcome high
        run: echo "high"
      - name: download
        uses: actions/download-artifact@v4
        with:
          name: file.txt
      - name: content
        run: cat file.txt


